[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "easy boss protect unit toss laptop demand deposit festival enjoy lounge verify riot empty fruit tower warfare junior scissors confirm alley poverty domain curve"
